export const SET_BANNER_LIST = 'SET_BANNER_LIST'
export const SET_REQUEST_TOKEN = 'SET_REQUEST_TOKEN'
export const SET_CLEAR_REQUEST_TOKEN = 'SET_CLEAR_REQUEST_TOKEN'

// 用户
export const SET_USER_LOGIN = 'SET_USER_LOGIN'
export const SET_USER = 'SET_USER'
export const SET_USER_VALIDATE = 'SET_USER_VALIDATE'
export const SET_USER_PERMISSION = 'SET_USER_PERMISSION'

export const SET_ROUTE = 'SET_ROUTE'

export const SET_MENU_PERMISSION = 'SET_MENU_PERMISSION'
